import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import Header from "~/components/common/Header";
import { Toaster } from "~/components/ui/sonner";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <div className="bg-bg min-h-screen">
            <div className="mx-auto w-full max-w-7xl">
              <Header />
              {children}
              <Toaster />
            </div>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
